name: Deploy Investo API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to deploy branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Deploy to the deploy branch
      - name: Deploy to deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git with token-based authentication
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Set the remote URL with token authentication using environment variables
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          # Create a temporary branch from the current HEAD
          git checkout -b temp-deploy-branch
          
          # Remove .github directory (which includes the workflow files)
          git rm -rf .github
          
          # Commit the change
          git commit -m "Remove workflow files for deploy branch"
          
          # Force push to deploy branch
          git push -f origin temp-deploy-branch:deploy
